#Project Setup
general:
  productiveBranch: 'master'
  jenkinsKubernetes:
    jnlpAgent: 'docker.wdf.sap.corp:50001/sap-production/jnlp-alpine:3.16.1-sap-01'

#Steps Specific Configuration
steps:
  mavenExecute:
#    dockerImage: 'maven:3.6.0-jdk-8'
    projectSettingsFile : ''

  cloudFoundryDeploy:
#    dockerImage: 's4sdk/docker-cf-cli'
    smokeTestStatusCode: '200'


#Stage Specific Configurations
stages:
  staticCodeChecks:
    findbugsExcludesFile: '' #Path to findbugs exclude file
    pmdExcludes: '' # List or ANT style patterns

  integrationTests:
    credentials:
      - alias: 'MOCK_SYSTEM'
        credentialId: 'MOCK_CREDS'

#  s4SdkQualityChecks:
#    jacocoExcludes:
#      - ''
#    nonErpDestinations:
#      - ''

  productionDeployment:
    cfTargets:
      - org: 'd069022'
        space: 'jwt-shizzle'
        apiEndpoint: 'https://api.cf.sap.hana.ondemand.com'
        appName: 'address-manager'
        manifest: 'manifest.yml'
        credentialsId: 'CF_DEPLOY'
